CREATE TABLE `TBSEQUENCIAS` (
  `CDSEQUENCIA` varchar(255) NOT NULL,
  `VLSEQUENCIA` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CDSEQUENCIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TBPAISES` (
  `IDPAIS` bigint(20) NOT NULL,
  `CDBACEN` varchar(4) DEFAULT NULL,
  `NMPAIS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`IDPAIS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TBESTADOS` (
  `IDESTADO` bigint(20) NOT NULL,
  `CDIBGE` varchar(7) DEFAULT NULL,
  `NMESTADO` varchar(100) DEFAULT NULL,
  `SGESTADO` varchar(2) DEFAULT NULL,
  `IDPAIS` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`IDESTADO`),
  KEY `FK42F07D7FC79308F` (`IDPAIS`),
  CONSTRAINT `FK42F07D7FC79308F` FOREIGN KEY (`IDPAIS`) REFERENCES `TBPAISES` (`IDPAIS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TBMUNICIPIOS` (
  `IDMUNICIPIO` bigint(20) NOT NULL,
  `CDIBGE` varchar(7) DEFAULT NULL,
  `NMMUNICIPIO` varchar(100) DEFAULT NULL,
  `IDESTADO` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`IDMUNICIPIO`),
  KEY `FKD0D1AB14AF698B65` (`IDESTADO`),
  CONSTRAINT `FKD0D1AB14AF698B65` FOREIGN KEY (`IDESTADO`) REFERENCES `TBESTADOS` (`IDESTADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `TBEMITENTES` (
  `IDEMITENTE` bigint(20) NOT NULL,
  `NRDOCUMENTO` varchar(20) DEFAULT NULL,
  `NMBAIRRO` varchar(100) DEFAULT NULL,
  `NRCEP` varchar(10) DEFAULT NULL,
  `NRFONE1` varchar(15) DEFAULT NULL,
  `VLLATITUDE` double DEFAULT NULL,
  `DSLOGRADOURO` varchar(100) DEFAULT NULL,
  `VLLONGITUDE` double DEFAULT NULL,
  `NRENDERECO` varchar(20) DEFAULT NULL,
  `NRINSCESTADUAL` varchar(20) DEFAULT NULL,
  `NMEMITENTE` varchar(100) DEFAULT NULL,
  `IDESTADO` bigint(20) DEFAULT NULL,
  `IDMUNICIPIO` bigint(20) DEFAULT NULL,
  `IDPAIS` bigint(20) DEFAULT NULL,
  `IDCLIENTE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`IDEMITENTE`),
  KEY `FKB4154418C79308F` (`IDPAIS`),
  KEY `FKB4154418AF698B65` (`IDESTADO`),
  KEY `FKB41544186F84A4A1` (`IDMUNICIPIO`),
  KEY `FKB415441815E273AF` (`IDCLIENTE`),
  CONSTRAINT `FKB415441815E273AF` FOREIGN KEY (`IDCLIENTE`) REFERENCES `TBUSUARIO` (`IDUSUARIO`),
  CONSTRAINT `FKB41544186F84A4A1` FOREIGN KEY (`IDMUNICIPIO`) REFERENCES `TBMUNICIPIOS` (`IDMUNICIPIO`),
  CONSTRAINT `FKB4154418AF698B65` FOREIGN KEY (`IDESTADO`) REFERENCES `TBESTADOS` (`IDESTADO`),
  CONSTRAINT `FKB4154418C79308F` FOREIGN KEY (`IDPAIS`) REFERENCES `TBPAISES` (`IDPAIS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `TBEMPRESA` (
  `IDEMPRESA` bigint(20) NOT NULL,
  `NMEMPRESA` varchar(120) DEFAULT NULL,
  `FLGSTATUS` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`IDEMPRESA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `TBPRODUTO` (
  `IDPRODUTO` bigint(20) NOT NULL,
  `DSCODIGO` varchar(100) DEFAULT NULL,
  `NMPRODUTO` varchar(100) DEFAULT NULL,
  `IDEMITENTE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`IDPRODUTO`),
  KEY `FK86DB58ABDCF75CB3` (`IDEMITENTE`),
  CONSTRAINT `FK86DB58ABDCF75CB3` FOREIGN KEY (`IDEMITENTE`) REFERENCES `TBEMITENTES` (`IDEMITENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `TBUSUARIO` (
  `IDUSUARIO` bigint(20) NOT NULL,
  `DSFONE` varchar(12) DEFAULT NULL,
  `NMLOGIN` varchar(250) NOT NULL,
  `NMNOME` varchar(50) DEFAULT NULL,
  `DSSENHA` varchar(20) NOT NULL,
  `DSSTATUS` varchar(20) NOT NULL,
  `DSTIPOUSUARIO` varchar(20) DEFAULT NULL,
  `IDEMITENTE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`IDUSUARIO`),
  KEY `FK91627CE0DCF75CB3` (`IDEMITENTE`),
  CONSTRAINT `FK91627CE0DCF75CB3` FOREIGN KEY (`IDEMITENTE`) REFERENCES `TBEMITENTES` (`IDEMITENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE TABLE `TBCLIENTES` (
  `IDCLIENTES` bigint(20) NOT NULL,
  `NRDOCUMENTO` varchar(20) DEFAULT NULL,
  `DSEMAIL` varchar(60) DEFAULT NULL,
  `NMBAIRRO` varchar(100) DEFAULT NULL,
  `NRCEP` varchar(10) DEFAULT NULL,
  `NRFONE1` varchar(15) DEFAULT NULL,
  `VLLATITUDE` double DEFAULT NULL,
  `DSLOGRADOURO` varchar(100) DEFAULT NULL,
  `VLLONGITUDE` double DEFAULT NULL,
  `NRENDERECO` varchar(20) DEFAULT NULL,
  `NRFONE` varchar(14) DEFAULT NULL,
  `NRINSCESTADUAL` varchar(20) DEFAULT NULL,
  `NMDESTINATARIO` varchar(100) DEFAULT NULL,
  `IDEMITENTE` bigint(20) DEFAULT NULL,
  `IDESTADO` bigint(20) DEFAULT NULL,
  `IDMUNICIPIO` bigint(20) DEFAULT NULL,
  `IDPAIS` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`IDCLIENTES`),
  KEY `FKC688E627C79308F` (`IDPAIS`),
  KEY `FKC688E627DCF75CB3` (`IDEMITENTE`),
  KEY `FKC688E627AF698B65` (`IDESTADO`),
  KEY `FKC688E6276F84A4A1` (`IDMUNICIPIO`),
  CONSTRAINT `FKC688E6276F84A4A1` FOREIGN KEY (`IDMUNICIPIO`) REFERENCES `TBMUNICIPIOS` (`IDMUNICIPIO`),
  CONSTRAINT `FKC688E627AF698B65` FOREIGN KEY (`IDESTADO`) REFERENCES `TBESTADOS` (`IDESTADO`),
  CONSTRAINT `FKC688E627C79308F` FOREIGN KEY (`IDPAIS`) REFERENCES `TBPAISES` (`IDPAIS`),
  CONSTRAINT `FKC688E627DCF75CB3` FOREIGN KEY (`IDEMITENTE`) REFERENCES `TBEMITENTES` (`IDEMITENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE TABLE `TBARQUIVOXML` (
  `IDARQUIVOXML` bigint(20) NOT NULL,
  `ARQUIVO` longblob,
  `DTDATAUPLOAD` datetime DEFAULT NULL,
  `NMARQUIVO` varchar(100) DEFAULT NULL,
  `FLGSTATUS` varchar(1) DEFAULT NULL,
  `notaFiscal_IDNOTAFISCAL` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`IDARQUIVOXML`),
  KEY `FK_TBARQUIVOXML_TBNOTAFISCAL_ID` (`notaFiscal_IDNOTAFISCAL`),
  CONSTRAINT `FK_TBARQUIVOXML_TBNOTAFISCAL_ID` FOREIGN KEY (`notaFiscal_IDNOTAFISCAL`) REFERENCES `TBNOTAFISCAL` (`IDNOTAFISCAL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `TBNOTAFISCAL` (
  `IDNOTAFISCAL` bigint(20) NOT NULL,
  `NRCHAVE` varchar(44) DEFAULT NULL,
  `NRDOCUMENTO` varchar(20) DEFAULT NULL,
  `DSEMAIL` varchar(60) DEFAULT NULL,
  `NRFONE` varchar(14) DEFAULT NULL,
  `NRINSCESTADUAL` varchar(20) DEFAULT NULL,
  `NMDESTINATARIO` varchar(100) DEFAULT NULL,
  `DTEMISSAO` datetime DEFAULT NULL,
  `DTIMPORTACAO` datetime DEFAULT NULL,
  `NMBAIRRO` varchar(100) DEFAULT NULL,
  `NRCEP` varchar(10) DEFAULT NULL,
  `NRFONE1` varchar(15) DEFAULT NULL,
  `VLLATITUDE` double DEFAULT NULL,
  `DSLOGRADOURO` varchar(100) DEFAULT NULL,
  `VLLONGITUDE` double DEFAULT NULL,
  `NRENDERECO` varchar(20) DEFAULT NULL,
  `DSMODELO` varchar(2) DEFAULT NULL,
  `DSNATOPER` varchar(60) DEFAULT NULL,
  `NRNOTA` varchar(9) DEFAULT NULL,
  `NRSERIE` varchar(3) DEFAULT NULL,
  `DSTIPOEMISSAO` varchar(2) DEFAULT NULL,
  `NRVALORTOTALNOTA` decimal(19,2) DEFAULT NULL,
  `NRVALORTOTALTRIBUTOS` decimal(19,2) DEFAULT NULL,
  `NRVERSAO` varchar(12) DEFAULT NULL,
  `arquivoXML_IDARQUIVOXML` bigint(20) DEFAULT NULL,
  `IDEMITENTE` bigint(20) DEFAULT NULL,
  `IDESTADO` bigint(20) DEFAULT NULL,
  `IDMUNICIPIO` bigint(20) DEFAULT NULL,
  `IDPAIS` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`IDNOTAFISCAL`),
  KEY `FK18B5841AC79308F` (`IDPAIS`),
  KEY `FK_TBNOTAFISCAL_TBEMITENTE_ID` (`IDEMITENTE`),
  KEY `FK18B5841AAF698B65` (`IDESTADO`),
  KEY `FK_TBNOTAFISCAL_TBARQUIVOXML_ID` (`arquivoXML_IDARQUIVOXML`),
  KEY `FK18B5841A6F84A4A1` (`IDMUNICIPIO`),
  CONSTRAINT `FK18B5841A6F84A4A1` FOREIGN KEY (`IDMUNICIPIO`) REFERENCES `TBMUNICIPIOS` (`IDMUNICIPIO`),
  CONSTRAINT `FK18B5841AAF698B65` FOREIGN KEY (`IDESTADO`) REFERENCES `TBESTADOS` (`IDESTADO`),
  CONSTRAINT `FK18B5841AC79308F` FOREIGN KEY (`IDPAIS`) REFERENCES `TBPAISES` (`IDPAIS`),
  CONSTRAINT `FK_TBNOTAFISCAL_TBARQUIVOXML_ID` FOREIGN KEY (`arquivoXML_IDARQUIVOXML`) REFERENCES `TBARQUIVOXML` (`IDARQUIVOXML`),
  CONSTRAINT `FK_TBNOTAFISCAL_TBEMITENTE_ID` FOREIGN KEY (`IDEMITENTE`) REFERENCES `TBEMITENTES` (`IDEMITENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE TABLE `TBITEMNOTAFISCAL` (
  `IDITEMNOTAFISCAL` bigint(20) NOT NULL,
  `NRCFOP` varchar(4) DEFAULT NULL,
  `NRORDEM` int(11) DEFAULT NULL,
  `DSCODIGO` varchar(100) DEFAULT NULL,
  `NMPRODUTO` varchar(100) DEFAULT NULL,
  `VLQUANTIDADE` double DEFAULT NULL,
  `DSUNIDADE` varchar(6) DEFAULT NULL,
  `VLTOTAL` decimal(19,2) DEFAULT NULL,
  `VLTOTALTRIBUTOS` decimal(19,2) DEFAULT NULL,
  `VLUNITARIO` decimal(19,2) DEFAULT NULL,
  `IDNOTAFISCAL_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`IDITEMNOTAFISCAL`),
  KEY `FK_TBITEMNOTAFISCAL_TBNOTAFISCAL_ID` (`IDNOTAFISCAL_ID`),
  CONSTRAINT `FK_TBITEMNOTAFISCAL_TBNOTAFISCAL_ID` FOREIGN KEY (`IDNOTAFISCAL_ID`) REFERENCES `TBNOTAFISCAL` (`IDNOTAFISCAL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;









